### ISSUE TITLE
Can it support Colab？

### ISSUE THREAD

**Issue by Michael-J98** [HyoungsungKim/Pytorch-tensorboard_tutorial#3]
Hi, 
it seems not working in colab.
Here is the code:
```
!pip install tensorboardX
import math
from tensorboardX import SummaryWriter
writer = SummaryWriter(logdir='scalar/tutorial')
for step in range(-360, 360):
    angle_rad = step * math.pi / 180
    writer.add_scalar('sin', math.sin(angle_rad), step)
    writer.add_scalar('cos', math.cos(angle_rad), step)
    writer.add_scalars('sin and cos', {'sin': math.sin(angle_rad), 'cos': math.cos(angle_rad)}, step)
writer.close()
!tensorboard --logdir scalar --port=6006
```
It output:
`2020-07-26 00:09:29.589262: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.2.2 at http://localhost:6006/ (Press CTRL+C to quit)`.
But when I clicked the link, I got `ERR_CONNECTION_REFUSED`.

**Comment by HyoungsungKim** [comment]
Thank you for making issue :)

In colab you have to use tensorboard extension

```
%load_ext tensorboard
%tensorboard --logdir /content/scalar
```

You can see a example in [here](https://colab.research.google.com/drive/1iQRdlJYFd4yjzZ7LkDbJCguStcpLRq3k?usp=sharing)

And you have to use **Chrome browser**. It did not work in firefox.

**Comment by Michael-J98** [comment]
Thanks, it worked！
BTW, how can tensorboard reflect data in real-time during training when using Pytorch. (without running the cell
 ```
%load_ext tensorboard
%tensorboard --logdir /content/scalar
``` 
again)

**Comment by HyoungsungKim** [comment]
After running once, it reloads data automatically every 30 sec.

Namely, tensorboard reflects new data every 30 second automatically. You don't need to run cell again.

Here is a [example](https://colab.research.google.com/drive/1iQRdlJYFd4yjzZ7LkDbJCguStcpLRq3k?usp=sharing)

**Comment by Michael-J98** [comment]
Oh~I see.
Thank you very much!
